I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/part2.rpy", line 136, in script
  File "renpy/common/000statements.rpy", line 543, in python
  File "game/part2.rpy", line 64, in python
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Users/ZERO/Computing/Ren'Py/renpy/execution.py", line 288, in run
    node.execute()
  File "/Users/ZERO/Computing/Ren'Py/renpy/ast.py", line 1531, in execute
    self.call("execute")
  File "/Users/ZERO/Computing/Ren'Py/renpy/ast.py", line 1544, in call
    renpy.statements.call(method, parsed, *args, **kwargs)
  File "/Users/ZERO/Computing/Ren'Py/renpy/statements.py", line 100, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 543, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "/Users/ZERO/Computing/Ren'Py/renpy/exports.py", line 1621, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "/Users/ZERO/Computing/Ren'Py/renpy/ui.py", line 237, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/Users/ZERO/Computing/Ren'Py/renpy/display/core.py", line 1853, in interact
    repeat, rv = self.interact_core(preloads=preloads, **kwargs)
  File "/Users/ZERO/Computing/Ren'Py/renpy/display/core.py", line 2092, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "/Users/ZERO/Computing/Ren'Py/renpy/display/core.py", line 250, in visit_all
    d.visit_all(callback)
  File "/Users/ZERO/Computing/Ren'Py/renpy/display/core.py", line 250, in visit_all
    d.visit_all(callback)
  File "/Users/ZERO/Computing/Ren'Py/renpy/display/core.py", line 250, in visit_all
    d.visit_all(callback)
  File "/Users/ZERO/Computing/Ren'Py/renpy/display/core.py", line 252, in visit_all
    callback(self)
  File "/Users/ZERO/Computing/Ren'Py/renpy/display/core.py", line 2092, in <lambda>
    root_widget.visit_all(lambda i : i.per_interact())
  File "/Users/ZERO/Computing/Ren'Py/renpy/display/screen.py", line 166, in per_interact
    self.update()
  File "/Users/ZERO/Computing/Ren'Py/renpy/display/screen.py", line 266, in update
    self.screen.function(**self.scope)
  File "/Users/ZERO/Computing/Ren'Py/renpy/screenlang.py", line 1217, in __call__
    renpy.python.py_exec_bytecode(self.code.bytecode, locals=scope)
  File "/Users/ZERO/Computing/Ren'Py/renpy/python.py", line 1297, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/part2.rpy", line 64, in <module>
    $affirmation = general_affirmation[random.randint(0,count)]
IndexError: list index out of range

Darwin-12.4.0-x86_64-i386-64bit
Ren'Py 6.15.7.374
Secure Self-Attachment Therapy 0.0
